
services:
  backend:
    build: ./backend
    container_name: bmw-api-container
    ports:
      - "3001:3001"
    environment:
      # Lê a variável do arquivo .env
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - bmw_db_data:/app/src/infrastructure/database

  frontend:
    build: ./frontend
    container_name: bmw-app-container
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - backend

volumes:
  bmw_db_data: